// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type User = {
  id: string;
  email: string;
  emailVerified?: boolean;
  name?: string;
  preferredUsername?: string;
  firstName?: string;
  lastName?: string;
  groups: string[];
  roles: string[];
};

export type Comment = {
  id: string;
  body: string;
  discussionId: string;
  author: User;
};
